import type { Metadata } from "next";
import { Lalezar, Inter } from "next/font/google"; // Removed Geist
import "@/styles/globals.css";
import { Navigation } from "@/components/layout/Navigation";

// Display Font (Headings)
const lalezar = Lalezar({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lalezar",
  display: "swap",
});

// Body Font (Text)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lalezar.variable} ${inter.variable}`}>
      <body className="antialiased">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
